# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    tag: latest
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gigauser
      POSTGRES_PASSWORD: 123ex#
      POSTGRES_DB: floorplanner
    volumes:
      - db-data:/var/lib/postgresql/data

  floorplanner:
    image: floorplanner
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DISPLAY=host.docker.internal:0.0
    depends_on:
      - db
volumes:
  db-data:

